### ISSUE TITLE
Turrets Randomly Go Crazy

### ISSUE THREAD

**Issue by mxnmnm** [SanAndreasP/TurretModRebirth#22] opened 2020-08-29 02:41 UTC
Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
14.23.5.2854

What version of SanLib do you use?
1.5.1

What version of Turret Mod Rebirth do you use?
4.0.0-beta.3

What is the issue/bug you have encountered? Give us a short description.
Turret starts spam shooting even though all of the targets are dead, it then spins around as if idle but it keeps on shooting in one specific direction. This usually happens in some modded dimensions (not 100% of the time)

How can it be reproduced?
Not sure but I've had the most success on some advanced rocketry planets or custom dimensions from just enough dimensions

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
https://imgur.com/a/DDLnGkM

https://gist.github.com/mxnmnm/c937e5b2cfa23a6236b850909d6b3248

**Comment by SanAndreaP** [comment] 2020-10-08 19:47
I've recoded the way a turret targets entities somewhat and fixed some issues. I cannot reproduce this in dev, so I assume it is fixed there now.
I'll close this issue now. When beta 4 is released and the issue persists, please open up a new issue.

**Closed as completed by SanAndreaP** 2020-10-08 19:47 UTC
Labels: bug, fixed in dev
